import random

class Data():

    numShuffles = 20
    data = []

    def __init__(self):
        self.BuildData()
        self.Shuffle()
        self.BuildDef()

    # Build dictionary
    def BuildData(self):
        # Words from Barron's Mil. Flight Aptitude Tests
        self.data.append(Word("abberation", "n", "a deviation from the standard; not typical"))
        self.data.append(Word("access", "n", "a means of approach or admittance"))
        self.data.append(Word("accord", "n", "an agreement"))
        self.data.append(Word("adage", "n", "wise proverb or saying"))
        self.data.append(Word("adversary", "n", "enemy, opponent"))
        self.data.append(Word("advocate", "n", "one who speaks in favor of or on behalf of another"))
        self.data.append(Word("affluence", "n", "wealth or abundance"))
        self.data.append(Word("agenda", "n", "list of items to discuss or to accomplish"))
        self.data.append(Word("alacrity", "n", "cheerful willingness or ready response"))
        self.data.append(Word("alias", "n", "an assumed name or pseudonym; used for purposes of deception"))
        self.data.append(Word("allusion", "n", "an indirect reference to something else, especially in literature; a hint"))
        self.data.append(Word("amity", "n", "friendship"))
        self.data.append(Word("anarchy", "n", "lawlessness, disorder; a lack of government control or effectiveness"))
        self.data.append(Word("anecdote", "n", "a brief, entertaining story"))
        self.data.append(Word("animosity", "n", "bitter hostility or open hatred"))
        self.data.append(Word("anomaly", "n", "an abnormality or irregularity"))
        self.data.append(Word("anthology", "n", "collection of writings, songs, or other creative works"))
        self.data.append(Word("apathy", "n", "indifference or lack of caring"))
        self.data.append(Word("apex", "n", "highest point"))
        self.data.append(Word("arbiter", "n", "one who decides; a judge"))
        self.data.append(Word("atlas", "n", "a book of maps"))
        self.data.append(Word("audacity", "n", "boldness"))
        self.data.append(Word("avarice", "n", "greed; desire for wealth"))
        self.data.append(Word("awe", "n", "deep feeling of respect and wonder"))
        self.data.append(Word("bastion", "n", "stronghold, fortress, fortified place"))
        self.data.append(Word("beacon", "n", "a guiding light to show the way or mark a spot"))
        self.data.append(Word("benediction", "n", "blessing; often given at the end of a ceremony"))
        self.data.append(Word("bias", "n", "prejudice or tendency in a certain direction"))
        self.data.append(Word("bigot", "n", "a person who is prejudiced against someone else because of race, religion, skin color, gender, etc."))
        self.data.append(Word("blasphemy", "n", "an insult to something held sacred"))
        self.data.append(Word("blemish", "n", "defect, stain, or flaw that takes away from the quality of th rest of the area/item"))
        self.data.append(Word("bondage", "n", "slavery"))
        self.data.append(Word("boon", "n", "benefit or gift"))
        self.data.append(Word("brawl", "n", "a noisy fight"))
        self.data.append(Word("brevity", "n", "shortness/conciseness"))
        self.data.append(Word("brochure", "n", "a pamphlet"))
        self.data.append(Word("bulwark", "n", "strong protection/barrier against enemy attacks"))
        self.data.append(Word("cacophony", "n", "a harsh or unpleasant mixture of sounds, voices, or words"))
        self.data.append(Word("caliber", "n", "litterally refers to size; bullet size in hundredths of an inch"))
        self.data.append(Word("camouflage", "n", "something that conceals people or things from the enemy"))
        self.data.append(Word("caste", "n", "social class or category"))
        self.data.append(Word("catastrophe", "n", "sudden disaster"))
        self.data.append(Word("chagrin", "n", "embarassment or disappointment"))
        self.data.append(Word("chronicle", "n", "historical record or listing, usually in chronological order"))
        self.data.append(Word("chronology", "n", "an order or listing of events, written or spoken"))
        self.data.append(Word("clamor", "n", "uproar"))
        self.data.append(Word("clemency", "n", "mercy"))
        self.data.append(Word("condolence", "n", "expression of sympathy to one who has suffered a loss"))
        self.data.append(Word("connoisseur", "n", "an expert judge of the best of something, such as wine"))
        self.data.append(Word("consensus", "n", "general or group agreement"))
        self.data.append(Word("context", "n", "the words or ideas surrounding one particular word or idea"))
        self.data.append(Word("conundrum", "n", "a perplexing puzzle or riddle"))
        self.data.append(Word("criterion", "n", "standard of judgment or comparison"))
        self.data.append(Word("crux", "n", "the essential point or central part"))
        self.data.append(Word("cynic", "n", "one who mocks or disbelieves the good intentions or values of others; one who believes people are motivated only by selfishness"))
        self.data.append(Word("data", "n", "facts or information"))
        self.data.append(Word("dearth", "n", "scarcity or lack of something"))
        self.data.append(Word("debacle", "n", "large-scale defeat or complete failure"))
        self.data.append(Word("debut", "n", "first appearance, especially before an audience"))
        self.data.append(Word("deference", "n", "conceding to another's desire or will; respect/courtesy"))
        self.data.append(Word("deluge", "n", "great flood or overwhelming inflow"))
        self.data.append(Word("depot", "n", "a warehouse, large storage place"))
        self.data.append(Word("depravity", "n", "moral corruption"))
        self.data.append(Word("destiny", "n", "predetermined fate"))
        self.data.append(Word("detriment", "n", "damage, loss, or disadvantage"))
        self.data.append(Word("diagnosis", "n", "analysis or determination of the cause of a disease or problem"))
        self.data.append(Word("diction", "n", "the way in which words are used by a speaker"))
        self.data.append(Word("discernment", "n", "insight, ability to see things clearly"))
        self.data.append(Word("disdain", "n", "arrogant scorn or contempt"))
        self.data.append(Word("dilemma", "n", "situation requiring a choice between two or more deeply held values, or between two or more unpleasant courses of action"))
        self.data.append(Word("din", "n", "loud, pervasive, continuous noise"))
        self.data.append(Word("directive", "n", "a general order or instruction"))
        self.data.append(Word("discord", "n", "disagreement, often noisy"))
        self.data.append(Word("discrepancy", "n", "inconsistency or error"))
        self.data.append(Word("discretion", "n", "freedom of choice; refers to a judicious reserve in one's speech or behavior"))
        self.data.append(Word("dissent", "n", "difference of opinion, especially from a widely held opinion"))
        self.data.append(Word("drought", "n", "long period of dry weather or conditions"))
        self.data.append(Word("effluvium", "n", "a disagreeable or bad-smelling vapor or gas"))
        self.data.append(Word("egotist", "n", "self-centered person"))
        self.data.append(Word("elite", "n", "person that is considered to be near the top (in society, for example)"))
        self.data.append(Word("enigma", "n", "mystery, puzzling circumstance"))
        self.data.append(Word("enterprise", "n", "an important project or self-sufficient organization"))
        self.data.append(Word("environment", "n", "general surroundings, either physical or referring to influences"))
        self.data.append(Word("epitome", "n", "a top-level representation of a quality, usually a virtue"))
        self.data.append(Word("epoch", "n", "a particular period of history, often remarkable or significant"))
        self.data.append(Word("era", "n", "a period of time"))
        self.data.append(Word("essence", "n", "basic nature"))
        self.data.append(Word("etiquette", "n", "generally accepted rules of social behavior"))
        self.data.append(Word("excerpt", "n", "passage quoted from a book or other document"))
        self.data.append(Word("exodus", "n", "departure, usually referring to a large group or large numbers"))
        self.data.append(Word("exposition", "n", "an explanation or expounding"))
        self.data.append(Word("facet", "n", "a side or aspect of a problem or situation"))
        self.data.append(Word("facsimile", "n", "exact copy or representation"))
        self.data.append(Word("fallacy", "n", "mistaken or erroneous idea, assumption, or conclusion"))
        self.data.append(Word("fantasy", "n", "imagined scenario or situation"))
        self.data.append(Word("fallacy", "n", "mistaken or erroneous idea, assumption, or conclusion"))
        self.data.append(Word("fervor", "n", "passion or enthusiasm"))        
        self.data.append(Word("feud", "n", "long-term disagreement or open hatred between individuals or groups"))
        self.data.append(Word("fisaco", "n", "disaster or complete failure"))
        self.data.append(Word("fiend", "n", "a cruel, hateful person"))
        self.data.append(Word("finale", "n", "the last part of a performance"))
        self.data.append(Word("flair", "n", "natural-seeming talent or style"))
        self.data.append(Word("flaw", "n", "defect or imperfection"))
        self.data.append(Word("focus", "n", "central point"))
        self.data.append(Word("foe", "n", "enemy, adversary, opponent"))
        self.data.append(Word("format", "n", "arrangement, especially of a document"))
        self.data.append(Word("forte", "n", "an area in which a person excels"))
        self.data.append(Word("fortitude", "n", "steady courage or strength"))
        self.data.append(Word("forum", "n", "a gathering or place where ideas or situations are discussed"))
        self.data.append(Word("foyer", "n", "the entrance hall to a building or dwelling"))
        self.data.append(Word("fraud", "n", "deliberate deception, especially an illegal one"))
        self.data.append(Word("friction", "n", "the surface of one object rubbing against another"))
        self.data.append(Word("function", "n", "the purpose sered by a person, object, or organization"))
        self.data.append(Word("furor", "n", "an outburst of excitement or disagreement"))
        self.data.append(Word("gamut", "n", "an entire range or spectrum of possible outcomes or conditions"))
        self.data.append(Word("genesis", "n", "beginning or origin"))
        self.data.append(Word("genre", "n", "a class or category, especially when referring to arts or entertainment"))
        self.data.append(Word("gist", "n", "essential content, central idea"))
        self.data.append(Word("glutton", "n", "one who overeats or indulges in anything to excess"))
        self.data.append(Word("grievance", "n", "a complaint made against an individual or organization; grudge"))
        self.data.append(Word("guile", "n", "cunning, deceit, duplicity"))
        self.data.append(Word("havoc", "n", "great damage, destruction, or confusion"))
        self.data.append(Word("hazard", "n", "danger or risk of injury"))
        self.data.append(Word("heresy", "n", "an opinion directly opposed to established beliefs"))
        self.data.append(Word("heritage", "n", "historical family, cultural, or organizational set of traditions"))
        self.data.append(Word("hindrance", "n", "obstacle or delaying obstruction"))
        self.data.append(Word("hoax", "n", "deliberate attempt to trick someone"))
        self.data.append(Word("horde", "n", "a multitude, great mass of people"))
        self.data.append(Word("horizon", "n", "farthest limit"))
        self.data.append(Word("hue", "n", "shade of color"))
        self.data.append(Word("hysteria", "n", "excessive or uncontrollable fear"))
        self.data.append(Word("idiom", "n", "regional or group jargon; literal meaning is different from intended meaning"))
        self.data.append(Word("illusion", "n", "an idea or impression that differs from reality"))
        self.data.append(Word("image", "n", "likeness or reflected or interpreted impression of a person, object, etc."))
        self.data.append(Word("impetus", "n", "a moving force or starting idea"))
        self.data.append(Word("incentive", "n", "motivation or benefit to doing something"))
        self.data.append(Word("incumbent", "n", "present holder of an office or a position"))
        self.data.append(Word("incursion", "n", "a hostile invasion"))
        self.data.append(Word("indolence", "n", "laziness"))
        self.data.append(Word("infirmity", "n", "physical disease, injury, or defect"))
        self.data.append(Word("influx", "n", "a flowing in of a substance, as of a wave or a flood"))
        self.data.append(Word("infraction", "n", "violation of a rule, regulation, or law"))
        self.data.append(Word("initiative", "n", "desire, idea, or ability to take the first step in carrying out some action"))
        self.data.append(Word("innovation", "n", "a new or improved way of doing something"))
        self.data.append(Word("integrity", "n", "moral and intellectual honesty and forthrightness"))
        self.data.append(Word("interim", "n", "a period of time between one event, process, or period and another"))
        self.data.append(Word("interlude", "n", "a short feature or period of time coming between two other, longer events"))
        self.data.append(Word("intrigue", "n", "secret plot or scheme"))
        self.data.append(Word("intuition", "n", "knowledge or conclusion obtained through instinct"))
        self.data.append(Word("invective", "n", "insulting or abusive speech"))
        self.data.append(Word("iota", "n", "a very small amount or piece"))
        self.data.append(Word("irony", "n", "a significant and often unexpected difference between what might be expected and what actually occurs"))
        self.data.append(Word("itinerary", "n", "agenda or schedule of events or places visited during a trip"))
        self.data.append(Word("jeopardy", "n", "risk of danger or harm"))
        self.data.append(Word("keynote", "n", "main theme or idea, usually referring to the main speech at a convention"))
        self.data.append(Word("larceny", "n", "theft, usually small"))
        self.data.append(Word("layman", "n", "a 'regular' person who is not a member of a technical or professional specialty"))
        self.data.append(Word("legacy", "n", "material or spiritual inheritance or heritage; historical perceptions"))
        self.data.append(Word("legend", "n", "unverified stories handed down from earlier times; can also refer to a person"))
        self.data.append(Word("legion", "n", "a large number of people; sometimes historically used as a designation of a military or paramilitary unit"))
        self.data.append(Word("lethargy", "n", "sluggishness, laziness, drowsiness"))
        self.data.append(Word("levee", "n", "a raised embankment designed to prevent flooding"))
        self.data.append(Word("levity", "n", "lightness, frivolity"))
        self.data.append(Word("liason", "n", "contact or coordination between two or more individuals or groups"))
        self.data.append(Word("litigation", "n", "legal proceedings"))
        self.data.append(Word("lore", "n", "body of traditional or historical knowledge"))
        self.data.append(Word("malady", "n", "disease or illness"))
        self.data.append(Word("maneuver", "n", "movement of a unit or an individual to achieve a goal"))
        self.data.append(Word("mania", "n", "abnormal concentration on or enthusiasm for something"))
        self.data.append(Word("marathon", "n", "26 miles, named after Greek messenger"))
        self.data.append(Word("maverick", "n", "a person who acts independently instead of in conformance with commonly expected behavior"))
        self.data.append(Word("maxim", "n", "an adage or proverb prescribing a rule or method of conduct"))
        self.data.append(Word("medium", "n", "means of communication of presentation"))
        self.data.append(Word("memento", "n", "object that commemorates or reminds someone of a past event"))
        self.data.append(Word("metropolis", "n", "a very large city"))
        self.data.append(Word("milieu", "n", "surroundings, environment"))
        self.data.append(Word("morale", "n", "the state of mind or attitude of an individual or a group"))
        self.data.append(Word("mores", "n", "established customs or values of a group or segment of society"))
        self.data.append(Word("multitude", "n", "a large number of something"))
        self.data.append(Word("myriad", "n", "a vast number or great multitude of something, usually with variation"))
        self.data.append(Word("myth", "n", "a traditional story, usually attempting to explain a natural condition"))
        self.data.append(Word("negligence", "n", "carelessness"))
        self.data.append(Word("neophyte", "n", "a beginner"))
        self.data.append(Word("niche", "n", "literally, a recess in a wall; figuratively an activity or situation that is especially well-suited for a person"))
        self.data.append(Word("nomad", "n", "a wanderer"))
        self.data.append(Word("nostalgia", "n", "a desire to return to a past experience or situation"))
        self.data.append(Word("oasis", "n", "an isolated place or area of comfort surrouned by desolation or barrenness"))
        self.data.append(Word("objective", "n", "a goal"))
        self.data.append(Word("oblivion", "n", "a condition of complete ignorance, forgetfulness, or unawareness"))
        self.data.append(Word("obscure", "n", "unclear, clouded, partially hidden"))
        self.data.append(Word("odyssey", "n", "a long journey"))
        self.data.append(Word("omen", "n", "a sign or an event believed to foretell the future"))
        self.data.append(Word("optimum", "n", "the best possible condition or combination of factors"))
        self.data.append(Word("ovation", "n", "applause of an audience, or positive reception accompanied by applause"))
        self.data.append(Word("oversight", "n", "an omission through error or carelessness"))
        self.data.append(Word("overture", "n", "first step, usually one that is intended to lead to others in action or discussion"))
        self.data.append(Word("panacea", "n", "a cure for all problems or diseases"))
        self.data.append(Word("panorama", "n", "an unobstructed view of a wide area"))
        self.data.append(Word("paradox", "n", "a statement that contradicts or appears to contradict itself"))
        self.data.append(Word("parsimony", "n", "stinginess; overzealous desire to be thrifty"))
        self.data.append(Word("partisan", "n", "one who supports a particular cause, person or idea; infiltrator that commits sabotage"))
        self.data.append(Word("pastime", "n", "a way of spending leisure time"))
        self.data.append(Word("pathology", "n", "the study of diseases"))
        self.data.append(Word("paucity", "n", "scarcity of a resource or condition"))
        self.data.append(Word("pauper", "n", "a very poor person"))
        self.data.append(Word("pedagogue", "n", "a strict, overly academic teacher or speaker"))
        self.data.append(Word("peer", "n", "an equal in age, social standing, professional rank, or ability"))
        self.data.append(Word("phenomenon", "n", "an unusual, noticeable, or outstanding occurrence that is directly perceived"))
        self.data.append(Word("philanthropy", "n", "love of mankind, usually exemplified by donations"))
        self.data.append(Word("phobia", "n", "unreasonable fear of something"))
        self.data.append(Word("physique", "n", "the build or physical condition of a human body"))
        self.data.append(Word("pilgrimage", "n", "long journey to some place or condition worthy of respect or devotion"))
        self.data.append(Word("pinnacle", "n", "highest point"))
        self.data.append(Word("pitfall", "n", "trap or obstacle for the unwary"))
        self.data.append(Word("pittance", "n", "very small amount, usually referring to money"))
        self.data.append(Word("plateau", "n", "an elevated, relatively level expanse of land; also can refer to a levelling-off of progress or results"))
        self.data.append(Word("plight", "n", "an unfavorable condition or situation"))
        self.data.append(Word("poise", "n", "calm and controlled behavior"))
        self.data.append(Word("populace", "n", "the people living in a certain area"))
        self.data.append(Word("posterity", "n", "future descendants or generations"))
        self.data.append(Word("precedent", "n", "event or law that serves as an example for later action"))
        self.data.append(Word("predecessor", "n", "someone or something that came before another"))
        self.data.append(Word("predicament", "n", "unpleasant problem or situation, usually one that is difficult to escape"))
        self.data.append(Word("preface", "n", "introductory statement or passage to a book, speech, or other communication"))
        self.data.append(Word("prelude", "n", "something that is preliminary to some act or event that is more important"))
        self.data.append(Word("premise", "n", "a statement or assumption from which a conclusion is drawn"))
        self.data.append(Word("premium", "n", "best quality"))
        self.data.append(Word("prestige", "n", "respect or status achieved through achievement or rank"))
        self.data.append(Word("pretext", "n", "a reason given as a cover-up for the real purpose for an action"))
        self.data.append(Word("priority", "n", "something that comes before others in significance or importance"))
        self.data.append(Word("probity", "n", "integrity, uprightness, honesty"))
        self.data.append(Word("process", "n", "a system or design for accomplishing a goal or an objective"))
        self.data.append(Word("prodigy", "n", "an extremely talented or gifted child"))
        self.data.append(Word("propinquity", "n", "nearness"))
        self.data.append(Word("propriety", "n", "good manners, appropriately respectful"))
        self.data.append(Word("prospect", "n", "possibility for the future"))
        self.data.append(Word("proviso", "n", "a requirement that something specific is done"))
        self.data.append(Word("prowess", "n", "strength or superior ability"))
        self.data.append(Word("proximity", "n", "nearness"))
        self.data.append(Word("pseudonym", "n", "an assumed name, usually a 'pen name'"))
        self.data.append(Word("pun", "n", "a play on words"))
        self.data.append(Word("pundit", "n", "a knowledgeable person in a particular field"))
        self.data.append(Word("quagmire", "n", "literally a bog or swamp; a difficult/dangerous situation"))
        self.data.append(Word("qualm", "n", "doubt or unease about some action or situation"))
        self.data.append(Word("quandary", "n", "deep uncertainty or indecision about a choice between two or more courses of action"))
        self.data.append(Word("query", "n", "a question or request for information"))
        self.data.append(Word("rampart", "n", "a fortification; bulwark or defense against attack"))
        self.data.append(Word("rapport", "n", "a harmonious or mutually trusting relationship"))
        self.data.append(Word("rarity", "n", "something that is infrequent or not commonly encountered"))
        self.data.append(Word("refuge", "n", "a place to which one can go for protection or separation from difficulty"))
        self.data.append(Word("remnant", "n", "remaining or left-over part of something"))
        self.data.append(Word("remorse", "n", "regret or guilt"))
        self.data.append(Word("renaissance", "n", "rebirth or revival"))
        self.data.append(Word("rendezvous", "n", "a meeting or location for a meeting"))
        self.data.append(Word("renown", "n", "fame or wide acclaim, especially for accomplishments or skill"))
        self.data.append(Word("replica", "n", "an exact copy or facsimile of something"))
        self.data.append(Word("reprimand", "n", "severe scolding or rebuke"))
        self.data.append(Word("reprisal", "n", "retaliation for real or perceived injuries"))
        self.data.append(Word("reprobate", "n", "a wicked, sinful, depraved person"))
        self.data.append(Word("reserves", "n", "a fighting force kept uncommitted until the need arises"))
        self.data.append(Word("residue", "n", "the remainder of something after removal of a part"))
        self.data.append(Word("resources", "n", "assets that are available for use, either material or spiritual"))
        self.data.append(Word("respite", "n", "a temporary break, usually one that brings relief"))
        self.data.append(Word("resume (resumay)", "n", "a written summary of work, education, accomplishments"))
        self.data.append(Word("reverence", "n", "a feeling of great respect, usually religious in nature"))
        self.data.append(Word("roster", "n", "a list of names"))
        self.data.append(Word("sabotage", "n", "deliberate damage to facilities or equipment belonging to an enemy"))
        self.data.append(Word("saga", "n", "a long story or tale, usually involving heroic deeds"))
        self.data.append(Word("salutations", "n", "a written or spoken greeting; also can refer to a person's title"))
        self.data.append(Word("sanction", "n", "approval, usually by a higher authority; can also mean a penalty for breaking a law or rule"))
        self.data.append(Word("sarcasm", "n", "cutting or insulting remarks"))
        self.data.append(Word("satire", "n", "criticism of someone or something by seeming approval cast in a light"))
        self.data.append(Word("scapegoat", "n", "someone who is blamed, usually unjustly, for the mistakes or misdeeds of others"))
        self.data.append(Word("scent", "n", "distinctive aroma or smell"))
        self.data.append(Word("scope", "n", "the complete area or extent of action or thought"))
        self.data.append(Word("sect", "n", "a group of people having the same beliefs, usually religious"))
        self.data.append(Word("semblance", "n", "outward appearance"))
        self.data.append(Word("sequel", "n", "something that follows from what has happened before"))
        self.data.append(Word("sham", "n", "a false imitation; slang - avoiding work"))
        self.data.append(Word("sheaf", "n", "a bundle, usually either of papers or grain"))
        self.data.append(Word("sheen", "n", "shine or luster"))
        self.data.append(Word("silhouette", "n", "the outline of a person or an object"))
        self.data.append(Word("site", "n", "a location"))
        self.data.append(Word("slander", "n", "spoken untruth that damages one's reputation"))
        self.data.append(Word("slogan", "n", "motto or saying that sums up a group or individual"))
        self.data.append(Word("slope", "n", "the angle of a surface that is neither vertical nor horizontal"))
        self.data.append(Word("snare", "n", "trap"))
        self.data.append(Word("solace", "n", "comfort after loss or disappointment"))
        self.data.append(Word("sponsor", "n", "one who supports and approves of a person or an activity"))
        self.data.append(Word("stagnation", "n", "motionlessness or inactivity"))
        self.data.append(Word("stamina", "n", "endurance; physical or mental"))
        self.data.append(Word("stanza", "n", "a section of a poem or song; a verse"))
        self.data.append(Word("stature", "n", "a height, measured physically or with respect"))
        self.data.append(Word("status", "n", "social or professional standing or level"))
        self.data.append(Word("stigma", "n", "mark or perception of disgrace or bad reputation"))
        self.data.append(Word("stimulus", "n", "an encouragement to act or react"))
        self.data.append(Word("strategy", "n", "planning and coordination aimed at achieving a goal"))
        self.data.append(Word("strife", "n", "conflict, disagreement, contention"))
        self.data.append(Word("summit", "n", "the highest point"))
        self.data.append(Word("supplement", "n", "an amount added to complete something"))
        self.data.append(Word("survey", "n", "a general study of a topic or issue"))
        self.data.append(Word("suspense", "n", "tenseness brought on by uncertainty about an outcome"))
        self.data.append(Word("sycophant", "n", "one who flatters a superior in hope of getting preferential treatment"))
        self.data.append(Word("symbol", "n", "a design or an insignia that represents something"))
        self.data.append(Word("symptom", "n", "an indication of a problem, usually referring to a disease or an illness"))
        self.data.append(Word("synopsis", "n", "brief summary"))
        self.data.append(Word("synthesis", "n", "the combining of parts to form a whole"))
        self.data.append(Word("tacit", "n", "silent or unspoken"))
        self.data.append(Word("tact", "n", "ability to give a message without causing offense"))
        self.data.append(Word("tactics", "n", "specific actions used to achieve a purpose or accomplish a goal"))
        self.data.append(Word("tally", "n", "a record or an account; sometimes of score"))
        self.data.append(Word("technique", "n", "a method or specific way of doing something"))
        self.data.append(Word("temerity", "n", "recklessness, audacity, boldness"))
        self.data.append(Word("temperament", "n", "overall attitude"))
        self.data.append(Word("tempo", "n", "the pace or speed of an activity"))
        self.data.append(Word("tension", "n", "mental or emotional strain"))
        self.data.append(Word("theme", "n", "the main topic of written work, movie, show, etc."))
        self.data.append(Word("threshold", "n", "the starting point of an activity; literally the line that separates one area from another"))
        self.data.append(Word("thrift", "n", "desire to spend money wisely"))
        self.data.append(Word("timbre", "n", "the quality of sound"))
        self.data.append(Word("tint", "n", "a shade of color"))
        self.data.append(Word("token", "n", "a sign or object that signifies a greater feeling or whole"))
        self.data.append(Word("tradition", "n", "customs and beliefs common to a group"))
        self.data.append(Word("trait", "n", "characteristic or distinguishing feature"))
        self.data.append(Word("transition", "n", "movement of one condition or situation or another"))
        self.data.append(Word("trepidation", "n", "fear, apprehension"))
        self.data.append(Word("tribunal", "n", "a place of judgment, usually legal in nature"))
        self.data.append(Word("tribute", "n", "a demonstration of respect or gratitude"))
        self.data.append(Word("turmoil", "n", "disturbance or upheaval"))
        self.data.append(Word("turpitude", "n", "shameful wickedness or depravity"))
        self.data.append(Word("tutor", "n", "a private teacher, often for a student who needs extra or specialized help"))
        self.data.append(Word("tycoon", "n", "a very wealthy and powerful business leader"))
        self.data.append(Word("ultimatum", "n", "a final demand or condition"))
        self.data.append(Word("upheaval", "n", "conflict or disturbance, usually characterized by a change in leadership, membership, or goals"))
        self.data.append(Word("utensil", "n", "implement or tool to help accomplish a task"))
        self.data.append(Word("utopia", "n", "ideal place or society"))
        self.data.append(Word("valor", "n", "courage/heroism"))
        self.data.append(Word("venture", "n", "a project or an enterprise, usually involving risk"))
        self.data.append(Word("vicinity", "n", "local area"))
        self.data.append(Word("victor", "n", "winner"))
        self.data.append(Word("vigor", "n", "vitality or energy"))
        self.data.append(Word("visionary", "n", "one with revolutionary or impractical goals or ideas about the future"))
        self.data.append(Word("volition", "n", "will or conscious choice"))
        self.data.append(Word("vow", "n", "solemn pledge or promise"))
        self.data.append(Word("wager", "n", "bet"))
        self.data.append(Word("welter", "n", "confused mass"))
        self.data.append(Word("whim", "n", "impulsive idea"))
        self.data.append(Word("woe", "n", "great trouble or sorrow"))
        self.data.append(Word("wrath", "n", "intense anger or fury"))
        self.data.append(Word("zeal", "n", "eager desire or enthusiasm"))
        self.data.append(Word("zenith", "n", "highest point"))
        self.data.append(Word("zest", "n", "enthusiasm"))

        self.data.append(Word("acquiesce", "v", "to give in; to agree"))
        self.data.append(Word("alleviate", "v", "to lessen or relieve discomfort or a bad situation"))
        self.data.append(Word("amass", "v", "to accumulate"))
        self.data.append(Word("ameliorate", "v", "to make better or more tolerable"))
        self.data.append(Word("appease", "v", "to soothe; to pacify by giving in"))
        self.data.append(Word("assuage", "v", "to soothe or comfort; to lessen the pain of"))
        self.data.append(Word("atrophy", "v", "to waste away from a lack of use"))
        self.data.append(Word("augment", "v", "to add or to increase"))
        self.data.append(Word("authorize", "v", "to give permission"))
        self.data.append(Word("belittle", "v", "to insult or to degrade"))
        self.data.append(Word("censor", "v", "to limit communication; to prevent the loss of secret information"))
        self.data.append(Word("censure", "v", "to condemn severely for inappropriate/rule-breaking behavior"))
        self.data.append(Word("coalesce", "v", "to come together as one; to unite"))
        self.data.append(Word("condescend", "v", "to patronize"))
        self.data.append(Word("condone", "v", "to approve of or allow"))
        self.data.append(Word("denounce", "v", "to speak out against"))
        self.data.append(Word("deride", "v", "to ridicule"))
        self.data.append(Word("desecrate", "v", "to profane a holy place"))
        self.data.append(Word("deter", "v", "to prevent or stop someone from doing something"))
        self.data.append(Word("digress", "v", "to veer off the main topic"))
        self.data.append(Word("discriminate", "v", "to differentiate or make a distinction"))
        self.data.append(Word("disparage", "v", "to belittle or say uncomplimentary things about someone or something"))
        self.data.append(Word("divert", "v", "to change course or direction of"))
        self.data.append(Word("drone", "v", "to talk on and on in a dull, boring way"))
        self.data.append(Word("efface", "v", "to erase or rub away the features of"))
        self.data.append(Word("emulate", "v", "to imitate as a role model"))
        self.data.append(Word("engender", "v", "to create or produce"))
        self.data.append(Word("enhance", "v", "to make better or improve"))
        self.data.append(Word("enthrall", "v", "to hold spellbound; captivate or charm"))
        self.data.append(Word("exemplify", "v", "to serve as an example"))
        self.data.append(Word("expedite", "v", "to make faster or easier"))
        self.data.append(Word("extol", "v", "to praise"))
        self.data.append(Word("facilitate", "v", "to make easier"))
        self.data.append(Word("heed", "v", "to listen to and obey"))
        self.data.append(Word("innovate", "v", "to create something new or better way of doing something"))
        self.data.append(Word("instigate", "v", "to provoke or stir up a controversy"))
        self.data.append(Word("languish", "v", "to become listless, hopeless or depressed"))
        self.data.append(Word("meander", "v", "to wander slowly or aimlessly"))
        self.data.append(Word("mitigate", "v", "to lessen the severity of something, such as a punishment"))
        self.data.append(Word("nullify", "v", "to cancel out entirely"))
        self.data.append(Word("preclude", "v", "to prevent or make impossible"))
        self.data.append(Word("refute", "v", "to disprove"))
        self.data.append(Word("rejuvinate", "v", "to renew or give new energy or strength"))
        self.data.append(Word("repress", "v", "to hold down"))
        self.data.append(Word("reproach", "v", "to scold or rebuke"))
        self.data.append(Word("repudiate", "v", "to reject or deny"))
        self.data.append(Word("rescind", "v", "to repeal or take back, formally"))
        self.data.append(Word("retract", "v", "to take back/withdraw"))
        self.data.append(Word("revere", "v", "to worship or respect very deeply"))
        self.data.append(Word("scrutinize", "v", "to examine closely"))
        self.data.append(Word("solicit", "v", "to ask for, to seek"))
        self.data.append(Word("squander", "v", "to waste"))
        self.data.append(Word("vacillate", "v", "to waver between alternatives; to be indecisive"))
        self.data.append(Word("veer", "v", "to turn aside or swerve away from a course"))
        self.data.append(Word("venerate", "v", "to revere or treat as something or someone holy"))
        self.data.append(Word("vilify", "v", "to cast as a villain; to defame"))
        
        self.data.append(Word("abstract", "a", "theoretical, lacking substance"))
        self.data.append(Word("acute", "a", "sharp, shrewd; also an angle < 90 degrees"))
        self.data.append(Word("aesthetic", "a", "having to do with art or artistic beauty"))
        self.data.append(Word("ambiguous", "a", "unclear"))
        self.data.append(Word("ambivalent", "a", "undecided"))
        self.data.append(Word("ambulatory", "a", "ability to walk"))
        self.data.append(Word("amiable", "a", "friendly or pleasant"))
        self.data.append(Word("animated", "a", "alive, lively"))
        self.data.append(Word("apocryphal", "a", "of doubtful or uncertain origin"))
        self.data.append(Word("apprehensive", "a", "worried, anxious"))
        self.data.append(Word("arrogant", "a", "feeling superior to others"))
        self.data.append(Word("articulate", "a", "well-spoken"))
        self.data.append(Word("ascetic", "a", "self-denying"))
        self.data.append(Word("astute", "a", "perceptive, intelligent"))
        self.data.append(Word("auspicious", "a", "favorable"))
        self.data.append(Word("austere", "a", "unadorned, forbiddingly bare"))
        self.data.append(Word("authentic", "a", "real/genuine"))
        self.data.append(Word("banal", "a", "unoriginal, boring"))
        self.data.append(Word("belligerent", "a", "combative/quarrelsome"))
        self.data.append(Word("benevolent", "a", "kind, generous"))
        self.data.append(Word("benign", "a", "gentle, not harmful"))
        self.data.append(Word("blithe", "a", "care-free, cheerful"))
        self.data.append(Word("candid", "a", "honest, forthright, frank"))
        self.data.append(Word("caustic", "a", "acidic or corrosive"))
        self.data.append(Word("complacent", "a", "smug, self-satisfied"))
        self.data.append(Word("compliant", "a", "yielding, submissive"))
        self.data.append(Word("conciliatory", "a", "peacemaking"))
        self.data.append(Word("concise", "a", "succinct"))
        self.data.append(Word("congenial", "a", "agreeably pleasant"))
        self.data.append(Word("conspicuous", "a", "obvious"))
        self.data.append(Word("contrite", "a", "deeply apologetic or remorseful"))
        self.data.append(Word("credulous", "a", "gullible"))
        self.data.append(Word("cryptic", "a", "mysterious, hard to understand"))
        self.data.append(Word("didactic", "a", "instructive"))
        self.data.append(Word("diffident", "a", "timid, lacking in self-confidence"))
        self.data.append(Word("diligent", "a", "hardworking"))
        self.data.append(Word("disparate", "a", "different, varied"))
        self.data.append(Word("dispassionate", "a", "without emotion; neutral"))
        self.data.append(Word("diverse", "a", "varied"))
        self.data.append(Word("dogmatic", "a", "arrogantly or overconfidently claiming the truth of unproven ideas"))
        self.data.append(Word("dubious", "a", "doubtful, uncertain"))
        self.data.append(Word("eccentric", "a", "unconventional, irregular"))
        self.data.append(Word("elaborate", "a", "a result of great effort and attention to detail"))
        self.data.append(Word("elusive", "a", "hard to capture or pin down"))
        self.data.append(Word("ephemeral", "a", "short-lived"))
        self.data.append(Word("esoteric", "a", "hard to understand, cryptic"))
        self.data.append(Word("exemplary", "a", "setting a superior example"))
        self.data.append(Word("exhaustive", "a", "very thorough and complete"))
        self.data.append(Word("expedient", "a", "meeting an immediate need"))
        self.data.append(Word("extraneous", "a", "irrelevant, extra, unnecessary"))
        self.data.append(Word("fallacious", "a", "false"))
        self.data.append(Word("fanatical", "a", "extremely devoted to or passionate about something"))
        self.data.append(Word("fastidious", "a", "meticulous, insistent on attention to detail"))
        self.data.append(Word("fickle", "a", "not faithful or consistent"))
        self.data.append(Word("flagrant", "a", "shocking or outrageous violation of a custom"))
        self.data.append(Word("fortuitous", "a", "luckily coincidental"))
        self.data.append(Word("frivolous", "a", "not serious, with levity"))
        self.data.append(Word("furtive", "a", "secretive"))
        self.data.append(Word("futile", "a", "hopeless"))
        self.data.append(Word("gullible", "a", "overly trusting"))
        self.data.append(Word("hackneyed", "a", "over-used"))
        self.data.append(Word("hedonistic", "a", "pleasure seeking"))
        self.data.append(Word("hypothetical", "a", "unproven"))
        self.data.append(Word("immutable", "a", "unchangeable, permanent"))
        self.data.append(Word("impartial", "a", "fair, unbiased, neutral"))
        self.data.append(Word("inadvertent", "a", "accidental"))
        self.data.append(Word("incessant", "a", "unceasing, never-ending"))
        self.data.append(Word("incoherent", "a", "jumbled, hard to understand"))
        self.data.append(Word("incongruous", "a", "inconsistent or inappropriate"))
        self.data.append(Word("insipid", "a", "dull, meaningless, empty"))
        self.data.append(Word("irascible", "a", "irritable"))
        self.data.append(Word("ironic", "a", "marked by an unexpected difference between what might be expected and what actually happens"))
        self.data.append(Word("laudable", "a", "worthy of praise"))
        self.data.append(Word("lax", "a", "careless"))
        self.data.append(Word("lucid", "a", "clear"))
        self.data.append(Word("marred", "a", "damaged, scarred"))
        self.data.append(Word("novel", "a", "new, original"))
        self.data.append(Word("objective", "a", "without bias"))
        self.data.append(Word("orthodox", "a", "conventional"))
        self.data.append(Word("pedestrian", "a", "common, ordinary"))
        self.data.append(Word("peripheral", "a", "unimportant"))
        self.data.append(Word("pervasive", "a", "a quality of being present throughout, permeating"))
        self.data.append(Word("pious", "a", "reverent or devout"))
        self.data.append(Word("pivotal", "a", "crucial, result-changing"))
        self.data.append(Word("pragmatic", "a", "practical"))
        self.data.append(Word("pretentious", "a", "pompous, self-important"))
        self.data.append(Word("prodigal", "a", "extravagant"))
        self.data.append(Word("prodigious", "a", "enormous; extraordinary size"))
        self.data.append(Word("profound", "a", "deep, insightful"))
        self.data.append(Word("profuse", "a", "extravagant, free-flowing"))
        self.data.append(Word("prosaic", "a", "dull, unimaginative"))
        self.data.append(Word("provincial", "a", "limited in outlook to one's own small area, narrow"))
        self.data.append(Word("provocative", "a", "exciting; attracting attention"))
        self.data.append(Word("prudent", "a", "careful, wisely cautious"))
        self.data.append(Word("recalcitrant", "a", "stubbornly defiant of authority or control"))
        self.data.append(Word("redundant", "a", "repetitive, unnecessary"))
        self.data.append(Word("relevant", "a", "important to the matter at hand"))
        self.data.append(Word("reprehensible", "a", "worthy of blame, disgraceful"))
        self.data.append(Word("resolute", "a", "firm, determined, unwavering in the face of challenges"))
        self.data.append(Word("reticent", "a", "restrained, uncommunicative"))
        self.data.append(Word("rigorous", "a", "strict"))
        self.data.append(Word("saccharine", "a", "overly sweet or flattering"))
        self.data.append(Word("sage", "a", "wise, knowledgeable"))
        self.data.append(Word("scanty", "a", "inadequate, minimal"))
        self.data.append(Word("scrupulous", "a", "strict or careful in an ethical sense"))
        self.data.append(Word("servile", "a", "submissive and subservient"))
        self.data.append(Word("skeptical", "a", "doubting"))
        self.data.append(Word("solemn", "a", "grave, serious"))
        self.data.append(Word("static", "a", "stationary, not moving"))
        self.data.append(Word("stoic", "a", "outwardly indifferent to circumstances"))
        self.data.append(Word("stringent", "a", "strict or restrictive"))
        self.data.append(Word("subtle", "a", "not obvious; also - able to make fine distinctions"))
        self.data.append(Word("supercilious", "a", "haughty, insultingly patronizing"))
        self.data.append(Word("superficial", "a", "on the surface only; shallow; not thorough"))
        self.data.append(Word("taciturn", "a", "untalkative by nature"))
        self.data.append(Word("tangible", "a", "touchable, not imagined or figurative"))
        self.data.append(Word("tedious", "a", "boring, overly detailed for no reason"))
        self.data.append(Word("temperate", "a", "moderate or restrained"))
        self.data.append(Word("tenacious", "a", "dogged or determined in the pursuit of an objective"))
        self.data.append(Word("tentative", "a", "temporary; uncertain; experimental"))
        self.data.append(Word("timid", "a", "shy, afraid of attention"))
        self.data.append(Word("uniform", "a", "consistent throughout"))
        self.data.append(Word("unprecedented", "a", "happening for the first time ever; never seen before"))
        self.data.append(Word("vehement", "a", "strong, urgent, passionate"))
        self.data.append(Word("verbose", "a", "wordy, overly talkative"))
        self.data.append(Word("virulent", "a", "malignant, malicious, full of hate"))
        self.data.append(Word("volatile", "a", "highly unstable, explosive"))
        self.data.append(Word("voluminous", "a", "very large, spacious"))
        self.data.append(Word("willful", "a", "deliberate, obstinate, insistent on having one's own way"))
        self.data.append(Word("zealous", "a", "enthusiastically devoted to a cause or idea"))
        # END Barron's Mil. Flight Aptitude Tests

    # Shuffle dictionary numShuffles times
    def Shuffle(self):
        for _ in range (0, self.numShuffles):
            random.shuffle(self.data)

    # Build definition tables
    def BuildDef(self):
        for i in range(0, len(self.data)):
            defListLength = len(self.data[i].DefList)
            randCorrectIndex = random.randrange(defListLength)
            self.data[i].DefList[randCorrectIndex] = Definition(self.data[i].Def, True)
            for j in range(0, defListLength):
                if self.data[i].DefList[j] == None:
                    choice: Word = random.choice(self.data)
                    # assert same definition is not added multiple times to a word
                    while choice.Def in self.data[i].DefList:
                        choice = random.choice(self.data)
                    self.data[i].DefList[j] = Definition(choice.Def, False)
                else:
                    continue

    # Call this method outside of this class
    def GetData(self):
        return self.data
    

class Word():

    Name = ""
    Type = ""
    Def = ""
    Redo = False

    # list of definitions of type [def:str, correct:bool]
    DefList = None

    def __init__(self, Name: str, Type: str, Def: str, DefList = None):
        self.Name = Name
        self.Type = Type
        self.Def = Def
        self.Redo = False
        if DefList == None:
            self.DefList = [ None ] * 4
        else:
            self.DefList = DefList

class Definition():
    Def = ""
    Correct = False

    def __init__(self, Def: str, Correct: bool):
        self.Def = Def
        self.Correct = Correct

    def __eq__(self, value):
        return self.Def == value
    
print("Usage: python main.py")